language: go

go:
  - 1.12

install:
  - ./install_metalinter.sh
  - go get -u github.com/jteeuwen/go-bindata/...

script:
  - ./lint_gofmt.sh
  - go-bindata -pkg bindata -o bindata/bindata.go html/...
  - ./lint_metalinter.sh
  - ./run_tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
