language: go

go:
  - 1.8

install:
  - ./install_metalinter.sh
  - go get -u github.com/jteeuwen/go-bindata/...

script:
  - go-bindata html/... bindata/bindata.go
  - ./lint_metalinter.sh
  - ./lint_gofmt.sh
  - ./run_tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
